### PR TITLE
Move sketch to appropriately named subfolder

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE requires that a sketch be located in a folder of the same name. Although the name of the repository does match the sketch name, when GitHub's popular Clone or download > Download ZIP feature is used to download the contents of a repository the branch/tag/commit name is appended to the folder name, causing a mismatch.

When opening a file that does not meet this sketch/folder name matching requirement the Arduino IDE presents a dialog:
```
The file "G27_Pedals_and_Shifter.ino" needs to be inside a sketch folder named "G27_Pedals_and_Shifter".
Create this folder, move the file, and continue?
```
After clicking "OK" the Arduino IDE currently moves only the file G27_Pedals_and_Shifter.ino to the new folder, leaving behind the other source files. This causes compilation of the sketch to fail:
```
G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino:8:36: fatal error: ./lib/G27PedalsShifter.h: No such file or directory
```

Fixes https://github.com/functionreturnfunction/G27_Pedals_and_Shifter/issues/16

### CODE REVIEW

**Comment by per1234** [comment]
I resolved the merge conflict via a force push.

**Comment by functionreturnfunction** [comment]
@per1234 I have a v2 with a desktop application for calibration that I was never able to finish because I've moved on to better pedals and shifter. Do you have a G27 that you're using this with?

**Comment by per1234** [comment]
No, I don't own a G27. I only saw the bug report https://github.com/functionreturnfunction/G27_Pedals_and_Shifter/issues/16 and wanted to make a contribution to the project by fixing it.

**Comment by functionreturnfunction** [comment]
Ah, well thanks for the help anyway.

**Pull request merged**
